application: tennis-1012
version: 1
runtime: php55
api_version: 1

handlers:
# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

- url: /(.*\.(js|json))
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: \1
  upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)

- url: /(.+)/
  static_files: \1/index.html
  upload: (.+)/index.html

- url: /(.*)/
  static_files: \1/index.html
  upload: (.*)/index.html

- url: /
  script: index.html

