/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides

Ext.Loader.setConfig({

});

Ext.application({
    name: 'TTApp',
    fullscreen : true,
    useLoadMask : true,

    requires: [
        'Ext.data.Operation',
        'Ext.data.reader.Reader',
        'Ext.data.proxy.Rest',
        'Ext.MessageBox',
        'Ext.Panel',
        'Ext.form.FieldSet',
        'Ext.data.Store',
        'Ext.Carousel',
    ],
    
    models: [
        'Match',  //Task
        'Rally'
    ],

    controllers: [
        'Analytict',
        'Rallys',
        'Matchs',         //Tasks
        'MatchMenuBottom',
        'MatchEdit',
        'RallyEdit',
    ],

    stores: [
        'Matchs',    //Tasks
        'Genres',
        'MatchHistorys',
        'Rounds',
        'Categorys',
        'Events',
        'Rallys',

        'Players',
        'Gnames',
    ],

    views: [
        'Rally.Menu',
        'PlayerList',
        'GnameList',
        'SideMenu',
        'MainView',
        'MatchList', //TaskList
        'MatchFormPanel',
        'RallyList',
        'MatchActMenu',
        'RallyPanel_s',

        'Rally.ServerBar',
        'Rally.ScoreBar',

        'Analytic.Tablet'
        //'Rally.Timeout',
    ],
    

    launch: function() {
        Ext.create('TTApp.view.MainView', {fullscreen: true});
        //Ext.Viewport.add('TTApp.view.MainView');

        Ext.Viewport.setMenu(Ext.create('TTApp.view.SideMenu'), {
            side: 'left',
            reveal: true
        });

        Ext.Viewport.add(Ext.create('TTApp.view.MatchActMenu'));
        Ext.Viewport.add(Ext.create('TTApp.view.Rally.Menu'));
    }

});